name: salonspa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  printing: ^5.14.2
  pdf: ^3.11.3
  intl: ^0.20.2
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  shared_preferences: ^2.5.3

  # --- added for local + offline ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4          # not used on web; safe on desktop/mobile
  connectivity_plus: ^6.0.3      # to know when to flush queued writes
  uuid: ^4.4.2                   # to make stable local IDs before syncing
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # (no code generation needed since we’ll store JSON maps in Hive)

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf
