// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyymS6OxsyLJXPP-WIQHQEZLO19vgIc30',
    appId: '1:930572192382:web:5336a1e8eff0ad9c7ce62f',
    messagingSenderId: '930572192382',
    projectId: 'spasalonmanagement',
    authDomain: 'spasalonmanagement.firebaseapp.com',
    storageBucket: 'spasalonmanagement.firebasestorage.app',
    measurementId: 'G-ZQJQ2M76WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlE8wHkDtMFyEON9DYXM8SH1uDNd3mXIA',
    appId: '1:930572192382:android:5d776b4d3a5b47d17ce62f',
    messagingSenderId: '930572192382',
    projectId: 'spasalonmanagement',
    storageBucket: 'spasalonmanagement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYv_7vKi9JgxgBZgR28iJD1pTj_cAwVuA',
    appId: '1:930572192382:ios:875efaf9536c7cc37ce62f',
    messagingSenderId: '930572192382',
    projectId: 'spasalonmanagement',
    storageBucket: 'spasalonmanagement.firebasestorage.app',
    iosBundleId: 'com.example.salonspa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYv_7vKi9JgxgBZgR28iJD1pTj_cAwVuA',
    appId: '1:930572192382:ios:875efaf9536c7cc37ce62f',
    messagingSenderId: '930572192382',
    projectId: 'spasalonmanagement',
    storageBucket: 'spasalonmanagement.firebasestorage.app',
    iosBundleId: 'com.example.salonspa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyymS6OxsyLJXPP-WIQHQEZLO19vgIc30',
    appId: '1:930572192382:web:19c7fdc47f149ffd7ce62f',
    messagingSenderId: '930572192382',
    projectId: 'spasalonmanagement',
    authDomain: 'spasalonmanagement.firebaseapp.com',
    storageBucket: 'spasalonmanagement.firebasestorage.app',
    measurementId: 'G-X624P649G8',
  );
}
